# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, b'Downvote'), (1, b'Upvote')], db_index=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('entry', 'user')]),
        ),
    ]
