sudo: false
language: python
python:
  - 2.7

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE flamingo;" -U postgres

script:
  - cd flamingo
  - python manage.py migrate
  - coverage run --source=. ./manage.py test

after_success:
  - coveralls
