sudo: false
language: python
python:
  - 3.6

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE flamingo;" -U postgres
  - export FLAMINGO_SECRET_KEY='-3f5yh\&\(s5%9uigtx^yn=t_woj0@90__fr\!t2b*96f5xoyzb%b'

script:
  - cd flamingo
  - python manage.py migrate
  - python manage.py collectstatic --no-input
  - coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
