dist: xenial
language: python
python:
  - 3.8
addons:
  postgresql: "9.6"

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - createdb flamingo
  - cp .env-sample .env

script:
  - poetry run inv check.all
  - poetry run ./manage.py collectstatic --noinput
  - poetry run coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
