[tool.poetry]
name = "flamingo"
version = "0.1.0"
description = "A photo contest web application."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2.4"
psycopg2 = "^2.8.3"
Pillow = "^6.1.0"
django-classbasedsettings = "^1.5.0"
python-memcached = "^1.59"
dj-database-url = "^0.5.0"
sorl-thumbnail = "^12.5.0"
whitenoise = "^4.1.3"
django-s3-storage = "^0.12.5"
python-dotenv = "^0.10.3"

[tool.poetry.dev-dependencies]
coverage = "^4.5.4"
django-pigeon = "^0.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
