[tool.poetry]
name = "flamingo"
version = "0.1.0"
description = "A photo contest web application."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2.10"
psycopg2 = "^2.8.4"
Pillow = "^7.0.0"
django-classbasedsettings = "^1.5.0"
python-memcached = "^1.59"
dj-database-url = "^0.5.0"
sorl-thumbnail = "^12.6.3"
whitenoise = "^5.0.1"
django-s3-storage = "^0.13.0"
python-dotenv = "^0.10.5"

[tool.poetry.dev-dependencies]
coverage = "^5.0.4"
django-pigeon = "^0.3.0"
black = {version = "^19.10b0",allow-prereleases = true}
pyupgrade = "^1.26"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
