# Generated by Django 3.0.5 on 2020-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0003_auto_20160131_0403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Downvote"), (1, "Upvote")], db_index=True
            ),
        ),
    ]
