# Generated by Django 3.0.5 on 2020-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo", name="img", field=models.ImageField(upload_to="photo"),
        ),
    ]
